apiVersion: skaffold/vwbeta2
kind: Config
build:
  local:
    push: false # everytime skaffold builds an image locally, don't push it
  artifacts: 
    - image: jparkkennaby/complex-client
      context: client
      docker: 
        dockerfile: Dockerfile.dev
      sync: # skaffold - mode 2: syncing files - # anytime skaffold see's a spectific type of file change, sync it to the file in the container
        '**/*js': . 
        '**/*css': . 
        '**/*html': . 
    - image: jparkkennaby/complex-server
      context: server
      docker: 
        dockerfile: Dockerfile.dev
        sync:
          '**/*js': .
    - image: jparkkennaby/complex-worker
      context: worker
      docker: 
        dockerfile: Dockerfile.dev
        sync:
          '**/*js': .
      
deploy: # automatically attempts to apply server at start up ($ skaffold dev), and delete at shit down (ctr + c)
  kubectl:
    manifests:
      - k8s/client-deployment.yaml 
      - k8s/server-deployment.yaml
      - k8s/worker-deployment.yaml
      - k8s/server-cluster-ip-service.yaml
      - k8s/client-cluster-ip-service.yaml
    # don't add services with persistant data (databases). skaffold will delete them