apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kubernetes-joepk-co-uk-tls # domain representation
spec:
  secretName: kubernetes-joepk-co-uk
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer # issuer.yaml
  commonName: kubernetes.joepk.co.uk # domain name the certificate will be valid for
  dnsNames: # list of all domains associated with the certifiate
    - kubernetes.joepk.co.uk
    - www.kubernetes.joepk.co.uk
        