apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server  
  template:
    metadata:
      labels: 
        component: server
    spec:
      containers:
        - name: server
          image: jparkkennaby/complex-server
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service # (See redis-cluster-id-service.yaml)
            - name: REDIS_PORT
              value: 6479 # (See redis-cluster-id-service.yaml)
            - name: PGUSER
              value: postgres # default postgres user
            - name: PGHOST
              value: postgres-cluster-ip-service # (See postgres-cluster-ip-service.yaml)
            - name: PGPORT
              value: 5432 # default postgres port
            - name: PGDATABASE
              value: postgres # default postgres database
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef: # environment variable set using $ kubectl create secret generic ...
                  name: pgpassword
                  key: PGPASSWORD